2024-06-20 13:41:44 | INFO | model_worker | Register to controller
2024-06-20 13:42:29 | INFO | model_worker | Send heart beat. Models: ('zhipu-api',). Semaphore: Semaphore(value=5, locked=False). call_ct: 0. worker_id: 420a4b03. 
2024-06-20 13:43:14 | INFO | model_worker | Send heart beat. Models: ('zhipu-api',). Semaphore: Semaphore(value=5, locked=False). call_ct: 0. worker_id: 420a4b03. 
2024-06-20 13:43:59 | INFO | model_worker | Send heart beat. Models: ('zhipu-api',). Semaphore: Semaphore(value=5, locked=False). call_ct: 0. worker_id: 420a4b03. 
2024-06-20 13:44:45 | INFO | model_worker | Send heart beat. Models: ('zhipu-api',). Semaphore: Semaphore(value=5, locked=False). call_ct: 0. worker_id: 420a4b03. 
2024-06-20 13:45:30 | INFO | model_worker | Send heart beat. Models: ('zhipu-api',). Semaphore: Semaphore(value=5, locked=False). call_ct: 0. worker_id: 420a4b03. 
2024-06-20 13:46:15 | INFO | model_worker | Send heart beat. Models: ('zhipu-api',). Semaphore: Semaphore(value=5, locked=False). call_ct: 0. worker_id: 420a4b03. 
2024-06-20 13:47:00 | INFO | model_worker | Send heart beat. Models: ('zhipu-api',). Semaphore: Semaphore(value=5, locked=False). call_ct: 0. worker_id: 420a4b03. 
2024-06-20 13:47:00 | ERROR | model_worker | heart beat error: HTTPConnectionPool(host='localhost', port=21001): Max retries exceeded with url: /receive_heart_beat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f86882e04c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-06-20 13:47:05 | INFO | model_worker | Register to controller
