nohup: ignoring input
[I 2024-06-27 10:18:34.352 ServerApp] Package jupyterlab took 0.0000s to import
[I 2024-06-27 10:18:34.384 ServerApp] Package jupyter_lsp took 0.0308s to import
[W 2024-06-27 10:18:34.384 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2024-06-27 10:18:34.389 ServerApp] Package jupyter_server_fileid took 0.0045s to import
[I 2024-06-27 10:18:34.401 ServerApp] Package jupyter_server_terminals took 0.0116s to import
[I 2024-06-27 10:18:34.465 ServerApp] Package jupyter_server_ydoc took 0.0639s to import
[I 2024-06-27 10:18:34.471 ServerApp] Package nbclassic took 0.0049s to import
[W 2024-06-27 10:18:34.474 ServerApp] A `_jupyter_server_extension_points` function was not found in nbclassic. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2024-06-27 10:18:34.474 ServerApp] Package notebook took 0.0000s to import
[I 2024-06-27 10:18:34.477 ServerApp] Package notebook_shim took 0.0000s to import
[W 2024-06-27 10:18:34.477 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2024-06-27 10:18:35.476 ServerApp] Package panel.io.jupyter_server_extension took 0.9979s to import
[I 2024-06-27 10:18:35.477 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-06-27 10:18:35.480 ServerApp] jupyter_server_fileid | extension was successfully linked.
[I 2024-06-27 10:18:35.485 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-06-27 10:18:35.488 ServerApp] jupyter_server_ydoc | extension was successfully linked.
[W 2024-06-27 10:18:35.493 ServerApp] ServerApp.password config is deprecated in 2.0. Use PasswordIdentityProvider.hashed_password.
[I 2024-06-27 10:18:35.493 ServerApp] jupyterlab | extension was successfully linked.
[W 2024-06-27 10:18:35.496 NotebookApp] 'notebook_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2024-06-27 10:18:35.496 NotebookApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2024-06-27 10:18:35.498 ServerApp] notebook_dir is deprecated, use root_dir
[I 2024-06-27 10:18:35.501 ServerApp] nbclassic | extension was successfully linked.
[W 2024-06-27 10:18:35.503 JupyterNotebookApp] 'notebook_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2024-06-27 10:18:35.503 JupyterNotebookApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2024-06-27 10:18:35.505 ServerApp] notebook | extension was successfully linked.
[I 2024-06-27 10:18:35.835 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-06-27 10:18:35.835 ServerApp] panel.io.jupyter_server_extension | extension was successfully linked.
[I 2024-06-27 10:18:35.860 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-06-27 10:18:44.202 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-06-27 10:18:44.203 FileIdExtension] Configured File ID manager: ArbitraryFileIdManager
[I 2024-06-27 10:18:44.203 FileIdExtension] ArbitraryFileIdManager : Configured root dir: /home/Work/00.Work_muyu
[I 2024-06-27 10:18:44.204 FileIdExtension] ArbitraryFileIdManager : Configured database path: /root/.local/share/jupyter/file_id_manager.db
[I 2024-06-27 10:18:44.213 FileIdExtension] ArbitraryFileIdManager : Successfully connected to database file.
[I 2024-06-27 10:18:44.213 FileIdExtension] ArbitraryFileIdManager : Creating File ID tables and indices with journal_mode = DELETE
[I 2024-06-27 10:18:44.214 FileIdExtension] Attached event listeners.
[I 2024-06-27 10:18:44.214 ServerApp] jupyter_server_fileid | extension was successfully loaded.
[I 2024-06-27 10:18:44.216 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-06-27 10:18:44.217 ServerApp] jupyter_server_ydoc | extension was successfully loaded.
[I 2024-06-27 10:18:44.223 LabApp] JupyterLab extension loaded from /home/util/anaconda3/lib/python3.10/site-packages/jupyterlab
[I 2024-06-27 10:18:44.223 LabApp] JupyterLab application directory is /home/util/anaconda3/share/jupyter/lab
[I 2024-06-27 10:18:44.224 LabApp] Extension Manager is 'pypi'.
[I 2024-06-27 10:18:44.228 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-06-27 10:18:44.236 ServerApp] nbclassic | extension was successfully loaded.
[I 2024-06-27 10:18:44.240 ServerApp] notebook | extension was successfully loaded.
[I 2024-06-27 10:18:44.241 ServerApp] panel.io.jupyter_server_extension | extension was successfully loaded.
[I 2024-06-27 10:18:44.242 ServerApp] Serving notebooks from local directory: /home/Work/00.Work_muyu
[I 2024-06-27 10:18:44.242 ServerApp] Jupyter Server 2.10.0 is running at:
[I 2024-06-27 10:18:44.242 ServerApp] http://4U:8006/lab
[I 2024-06-27 10:18:44.242 ServerApp]     http://127.0.0.1:8006/lab
[I 2024-06-27 10:18:44.242 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2024-06-27 10:18:44.490 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[I 2024-06-27 10:19:13.775 ServerApp] 302 GET / (@192.168.110.91) 1.33ms
[I 2024-06-27 10:19:13.781 LabApp] 302 GET /lab? (@192.168.110.91) 1.45ms
[I 2024-06-27 10:19:29.833 ServerApp] User a100870793c1426bafb8831fccd278cb logged in.
[I 2024-06-27 10:19:29.835 ServerApp] 302 POST /login?next=%2Flab%3F (a100870793c1426bafb8831fccd278cb@192.168.110.91) 84.90ms
[I 2024-06-27 10:19:32.779 LabApp] Build is up to date
[I 2024-06-27 10:19:33.363 ServerApp] Kernel started: 2541a665-e9d8-4f50-8d9b-8676f925ca8a
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
[I 2024-06-27 10:19:33.376 ServerApp] Kernel started: 5353634b-f2cf-4233-8ad5-23048f1b04f5
[I 2024-06-27 10:19:33.404 ServerApp] Kernel started: 7cf81b17-6bc1-42b1-83c2-649a94b21e38
[I 2024-06-27 10:19:33.497 ServerApp] Kernel started: 67128c2d-1b0c-4581-b6af-eede01c75662
[I 2024-06-27 10:19:33.515 ServerApp] Kernel started: baeb9567-5264-4d68-b010-6f45f6919e32
[W 2024-06-27 10:19:33.544 ServerApp] 404 PATCH http://192.168.110.131:8006/api/sessions/02b27fab-201a-4f02-a56c-9b784e2ad9dc?1719454780788 (a100870793c1426bafb8831fccd278cb@192.168.110.91) 30.47ms referer=http://192.168.110.131:8006/lab?
[W 2024-06-27 10:19:33.551 ServerApp] 404 PATCH http://192.168.110.131:8006/api/sessions/2dfd3f2a-14b5-466a-b0d4-2b6614e17742?1719454780788 (a100870793c1426bafb8831fccd278cb@192.168.110.91) 4.28ms referer=http://192.168.110.131:8006/lab?
[W 2024-06-27 10:19:33.554 ServerApp] 404 PATCH http://192.168.110.131:8006/api/sessions/d986569d-a737-471f-a130-d4d33c29e730?1719454780789 (a100870793c1426bafb8831fccd278cb@192.168.110.91) 5.99ms referer=http://192.168.110.131:8006/lab?
[W 2024-06-27 10:19:33.586 ServerApp] 404 PATCH http://192.168.110.131:8006/api/sessions/9cb1c265-4326-4503-a9ae-256b8e5888b3?1719454780864 (a100870793c1426bafb8831fccd278cb@192.168.110.91) 5.49ms referer=http://192.168.110.131:8006/lab?
[W 2024-06-27 10:19:33.588 ServerApp] 404 PATCH http://192.168.110.131:8006/api/sessions/d40e4690-707f-45a9-ba17-bc26d85c38f8?1719454780864 (a100870793c1426bafb8831fccd278cb@192.168.110.91) 6.88ms referer=http://192.168.110.131:8006/lab?
[W 2024-06-27 10:19:34.051 ServerApp] 404 PATCH http://192.168.110.131:8006/api/config/jupyterlabapputilsextensionannouncements?1719454781340 (a100870793c1426bafb8831fccd278cb@192.168.110.91) 3.18ms referer=http://192.168.110.131:8006/lab?
[I 2024-06-27 10:19:34.122 ServerApp] Connecting to kernel 67128c2d-1b0c-4581-b6af-eede01c75662.
[I 2024-06-27 10:19:34.132 ServerApp] Connecting to kernel baeb9567-5264-4d68-b010-6f45f6919e32.
[I 2024-06-27 10:19:34.134 ServerApp] Connecting to kernel baeb9567-5264-4d68-b010-6f45f6919e32.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[I 2024-06-27 10:19:34.444 ServerApp] Connecting to kernel 7cf81b17-6bc1-42b1-83c2-649a94b21e38.
[I 2024-06-27 10:19:34.450 ServerApp] Connecting to kernel 7cf81b17-6bc1-42b1-83c2-649a94b21e38.
[I 2024-06-27 10:19:34.570 ServerApp] Connecting to kernel 5353634b-f2cf-4233-8ad5-23048f1b04f5.
[I 2024-06-27 10:19:36.306 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), new random ports
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
[I 2024-06-27 10:19:39.324 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (2/5), new random ports
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
[I 2024-06-27 10:19:39.645 ServerApp] Starting buffering for 5353634b-f2cf-4233-8ad5-23048f1b04f5:50339117-6338-448d-af78-7c9df2f20d1b
[I 2024-06-27 10:19:39.646 ServerApp] Starting buffering for 7cf81b17-6bc1-42b1-83c2-649a94b21e38:fe275c63-b82b-4f1f-af1d-65ca823c3c70
[I 2024-06-27 10:19:39.647 ServerApp] Starting buffering for baeb9567-5264-4d68-b010-6f45f6919e32:01f65e79-c69d-4da4-aa42-08eab3d8e979
[I 2024-06-27 10:19:39.648 ServerApp] Starting buffering for 67128c2d-1b0c-4581-b6af-eede01c75662:97ff236a-dbe1-4481-bb43-949a8f698a87
[I 2024-06-27 10:19:39.969 ServerApp] Connecting to kernel 67128c2d-1b0c-4581-b6af-eede01c75662.
[I 2024-06-27 10:19:39.969 ServerApp] Restoring connection for 67128c2d-1b0c-4581-b6af-eede01c75662:97ff236a-dbe1-4481-bb43-949a8f698a87
[I 2024-06-27 10:19:40.047 ServerApp] Connecting to kernel baeb9567-5264-4d68-b010-6f45f6919e32.
[I 2024-06-27 10:19:40.048 ServerApp] Restoring connection for baeb9567-5264-4d68-b010-6f45f6919e32:01f65e79-c69d-4da4-aa42-08eab3d8e979
[I 2024-06-27 10:19:40.079 ServerApp] Connecting to kernel 7cf81b17-6bc1-42b1-83c2-649a94b21e38.
[I 2024-06-27 10:19:40.079 ServerApp] Restoring connection for 7cf81b17-6bc1-42b1-83c2-649a94b21e38:fe275c63-b82b-4f1f-af1d-65ca823c3c70
[I 2024-06-27 10:19:40.199 ServerApp] Connecting to kernel 5353634b-f2cf-4233-8ad5-23048f1b04f5.
[I 2024-06-27 10:19:40.199 ServerApp] Restoring connection for 5353634b-f2cf-4233-8ad5-23048f1b04f5:50339117-6338-448d-af78-7c9df2f20d1b
[I 2024-06-27 10:19:42.131 ServerApp] Kernel started: c6d3dde6-85de-4410-98a7-bd23726ef53a
[I 2024-06-27 10:19:42.340 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (3/5), new random ports
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[I 2024-06-27 10:19:43.068 ServerApp] Connecting to kernel c6d3dde6-85de-4410-98a7-bd23726ef53a.
[I 2024-06-27 10:19:43.100 ServerApp] Connecting to kernel c6d3dde6-85de-4410-98a7-bd23726ef53a.
[W 2024-06-27 10:19:43.121 ServerApp] Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0x7f707d56ab90>
[I 2024-06-27 10:19:43.135 ServerApp] Connecting to kernel c6d3dde6-85de-4410-98a7-bd23726ef53a.
[W 2024-06-27 10:19:43.173 ServerApp] Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0x7f707d39a6b0>
[I 2024-06-27 10:19:45.355 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (4/5), new random ports
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
[I 2024-06-27 10:19:46.839 ServerApp] Kernel started: 886c2b52-a9b9-442a-a6fd-52aadc363ec3
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[I 2024-06-27 10:19:47.531 ServerApp] Connecting to kernel 886c2b52-a9b9-442a-a6fd-52aadc363ec3.
[I 2024-06-27 10:19:48.372 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (5/5), new random ports
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
[I 2024-06-27 10:19:50.378 ServerApp] Kernel started: c96d31ef-967e-4d64-8218-eb5050832499
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
[W 2024-06-27 10:19:51.388 ServerApp] AsyncIOLoopKernelRestarter: restart failed
[W 2024-06-27 10:19:51.388 ServerApp] Kernel 2541a665-e9d8-4f50-8d9b-8676f925ca8a died, removing from map.
[I 2024-06-27 10:19:53.361 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), new random ports
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
[I 2024-06-27 10:19:55.901 ServerApp] Creating new notebook in 
[I 2024-06-27 10:19:56.078 ServerApp] Kernel started: 2c70e5d8-3d38-47c7-b7af-d61c968020c6
[I 2024-06-27 10:19:56.378 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (2/5), new random ports
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
[I 2024-06-27 10:19:59.392 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (3/5), new random ports
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
[I 2024-06-27 10:20:02.410 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (4/5), new random ports
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
[I 2024-06-27 10:20:05.429 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (5/5), new random ports
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
[W 2024-06-27 10:20:08.446 ServerApp] AsyncIOLoopKernelRestarter: restart failed
[W 2024-06-27 10:20:08.447 ServerApp] Kernel c96d31ef-967e-4d64-8218-eb5050832499 died, removing from map.
[I 2024-06-27 10:20:17.081 ServerApp] Connecting to kernel 2c70e5d8-3d38-47c7-b7af-d61c968020c6.
[E 2024-06-27 10:20:33.527 ServerApp] Uncaught exception GET /api/kernels/2541a665-e9d8-4f50-8d9b-8676f925ca8a/channels?session_id=7e61ba44-1011-491c-9aec-516c11812c0b (192.168.110.91)
    HTTPServerRequest(protocol='http', host='192.168.110.131:8006', method='GET', uri='/api/kernels/2541a665-e9d8-4f50-8d9b-8676f925ca8a/channels?session_id=7e61ba44-1011-491c-9aec-516c11812c0b', version='HTTP/1.1', remote_ip='192.168.110.91')
    Traceback (most recent call last):
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/services/kernels/websocket.py", line 64, in get
        await self.pre_get()
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/services/kernels/websocket.py", line 59, in pre_get
        await self.connection.prepare()
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 317, in prepare
        raise TimeoutError(msg)
    TimeoutError: Kernel never reached an 'alive' state.
[E 2024-06-27 10:20:33.545 ServerApp] {
      "Host": "192.168.110.131:8006",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
    }
[E 2024-06-27 10:20:33.545 ServerApp] 500 GET /api/kernels/2541a665-e9d8-4f50-8d9b-8676f925ca8a/channels?session_id=7e61ba44-1011-491c-9aec-516c11812c0b (a100870793c1426bafb8831fccd278cb@192.168.110.91) 60033.39ms referer=None
[W 2024-06-27 10:20:50.395 ServerApp] Timeout waiting for kernel_info reply from c96d31ef-967e-4d64-8218-eb5050832499
[E 2024-06-27 10:20:50.395 ServerApp] Uncaught exception GET /api/kernels/c96d31ef-967e-4d64-8218-eb5050832499/channels?session_id=f990c169-d28d-4f9f-bd45-977e4b1bc549 (192.168.110.91)
    HTTPServerRequest(protocol='http', host='192.168.110.131:8006', method='GET', uri='/api/kernels/c96d31ef-967e-4d64-8218-eb5050832499/channels?session_id=f990c169-d28d-4f9f-bd45-977e4b1bc549', version='HTTP/1.1', remote_ip='192.168.110.91')
    Traceback (most recent call last):
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/services/kernels/websocket.py", line 65, in get
        await super().get(kernel_id=kernel_id)
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/websocket.py", line 272, in get
        await self.ws_connection.accept_connection(self)
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/websocket.py", line 862, in accept_connection
        await self._accept_connection(handler)
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/websocket.py", line 902, in _accept_connection
        self.selected_subprotocol = handler.select_subprotocol(subprotocols)
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/services/kernels/websocket.py", line 87, in select_subprotocol
        preferred_protocol = self.connection.kernel_ws_protocol
    AttributeError: 'NoneType' object has no attribute 'kernel_ws_protocol'
[E 2024-06-27 10:20:50.409 ServerApp] {
      "Host": "192.168.110.131:8006",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
    }
[E 2024-06-27 10:20:50.409 ServerApp] 500 GET /api/kernels/c96d31ef-967e-4d64-8218-eb5050832499/channels?session_id=f990c169-d28d-4f9f-bd45-977e4b1bc549 (a100870793c1426bafb8831fccd278cb@192.168.110.91) 60017.91ms referer=None
[I 2024-06-27 10:21:33.070 ServerApp] Saving file at /Untitled5.ipynb
[I 2024-06-27 10:21:33.188 ServerApp] Saving file at /glm4.ipynb
[I 2024-06-27 10:21:33.240 ServerApp] Saving file at /Untitled7.ipynb
[I 2024-06-27 10:21:56.063 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 10:23:35.454 ServerApp] Kernel restarted: 2c70e5d8-3d38-47c7-b7af-d61c968020c6
[I 2024-06-27 10:23:35.460 ServerApp] Starting buffering for 2c70e5d8-3d38-47c7-b7af-d61c968020c6:2edc215b-4f75-485e-8d1f-631e1c62047a
[I 2024-06-27 10:23:35.467 ServerApp] Connecting to kernel 2c70e5d8-3d38-47c7-b7af-d61c968020c6.
[I 2024-06-27 10:23:35.467 ServerApp] Restoring connection for 2c70e5d8-3d38-47c7-b7af-d61c968020c6:2edc215b-4f75-485e-8d1f-631e1c62047a
[I 2024-06-27 10:23:56.134 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 10:25:56.212 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 10:27:56.295 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 10:28:53.029 ServerApp] Kernel restarted: 2c70e5d8-3d38-47c7-b7af-d61c968020c6
[I 2024-06-27 10:28:53.039 ServerApp] Starting buffering for 2c70e5d8-3d38-47c7-b7af-d61c968020c6:2edc215b-4f75-485e-8d1f-631e1c62047a
[I 2024-06-27 10:28:53.048 ServerApp] Connecting to kernel 2c70e5d8-3d38-47c7-b7af-d61c968020c6.
[I 2024-06-27 10:28:53.048 ServerApp] Restoring connection for 2c70e5d8-3d38-47c7-b7af-d61c968020c6:2edc215b-4f75-485e-8d1f-631e1c62047a
[I 2024-06-27 10:31:56.391 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 10:36:17.054 ServerApp] Kernel restarted: 2c70e5d8-3d38-47c7-b7af-d61c968020c6
[I 2024-06-27 10:36:17.065 ServerApp] Starting buffering for 2c70e5d8-3d38-47c7-b7af-d61c968020c6:2edc215b-4f75-485e-8d1f-631e1c62047a
[I 2024-06-27 10:36:17.075 ServerApp] Connecting to kernel 2c70e5d8-3d38-47c7-b7af-d61c968020c6.
[I 2024-06-27 10:36:17.075 ServerApp] Restoring connection for 2c70e5d8-3d38-47c7-b7af-d61c968020c6:2edc215b-4f75-485e-8d1f-631e1c62047a
[I 2024-06-27 10:37:56.464 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 10:39:56.540 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 10:41:56.634 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 10:43:56.719 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 10:45:56.815 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 10:47:56.917 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 10:49:57.018 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 10:51:31.954 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 11:11:40.099 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 11:13:40.220 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 11:15:40.326 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 11:19:41.123 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 11:21:41.230 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 11:23:41.337 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 11:25:41.466 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 11:27:41.578 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 11:29:41.702 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 11:31:10.738 ServerApp] Kernel restarted: 2c70e5d8-3d38-47c7-b7af-d61c968020c6
[I 2024-06-27 11:31:10.748 ServerApp] Starting buffering for 2c70e5d8-3d38-47c7-b7af-d61c968020c6:2edc215b-4f75-485e-8d1f-631e1c62047a
[I 2024-06-27 11:31:10.754 ServerApp] Connecting to kernel 2c70e5d8-3d38-47c7-b7af-d61c968020c6.
[I 2024-06-27 11:31:10.755 ServerApp] Restoring connection for 2c70e5d8-3d38-47c7-b7af-d61c968020c6:2edc215b-4f75-485e-8d1f-631e1c62047a
[I 2024-06-27 11:31:41.815 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 11:33:41.931 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 11:35:42.056 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 11:37:42.151 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 11:39:42.285 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 11:41:42.403 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 11:43:42.510 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 11:45:42.630 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 11:47:42.735 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 11:49:42.837 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 11:51:42.937 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 11:53:43.045 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 11:55:43.160 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 11:57:43.263 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 11:59:43.378 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 12:01:43.523 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 12:02:07.865 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 12:44:08.187 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 12:46:08.306 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 12:48:08.422 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 12:50:08.556 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 12:52:08.675 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 12:54:08.802 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 12:56:08.982 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 12:58:09.103 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 13:00:09.231 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 13:02:09.346 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 13:04:09.501 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 13:06:09.622 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 13:08:09.754 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 13:10:09.870 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 13:12:10.038 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 13:16:10.201 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 13:18:10.322 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 13:20:10.443 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 13:22:10.557 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 13:24:10.691 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 13:26:10.802 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 13:28:10.922 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 13:30:11.045 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 13:32:11.327 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 13:34:11.438 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 13:36:11.571 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 13:38:11.689 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 13:40:11.810 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 13:42:11.957 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 13:44:12.089 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 13:46:12.237 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 13:48:12.360 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 13:50:12.505 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 13:52:12.624 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 14:10:13.327 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 14:14:13.458 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 14:16:13.580 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 14:18:13.703 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 14:20:13.838 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 14:23:26.839 ServerApp] Starting buffering for 886c2b52-a9b9-442a-a6fd-52aadc363ec3:c2386a9d-0cb1-47cc-870e-a6b8092486cf
[I 2024-06-27 14:26:13.977 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 14:28:14.107 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 14:30:14.237 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 14:32:14.344 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 14:34:14.492 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 14:36:14.614 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 14:38:14.740 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 14:40:14.861 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 14:48:15.316 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 14:50:15.443 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 14:52:15.585 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 14:54:15.721 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 14:56:15.869 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 14:58:06.733 ServerApp] Kernel restarted: 2c70e5d8-3d38-47c7-b7af-d61c968020c6
[I 2024-06-27 14:58:06.743 ServerApp] Starting buffering for 2c70e5d8-3d38-47c7-b7af-d61c968020c6:2edc215b-4f75-485e-8d1f-631e1c62047a
[I 2024-06-27 14:58:06.750 ServerApp] Connecting to kernel 2c70e5d8-3d38-47c7-b7af-d61c968020c6.
[I 2024-06-27 14:58:06.750 ServerApp] Restoring connection for 2c70e5d8-3d38-47c7-b7af-d61c968020c6:2edc215b-4f75-485e-8d1f-631e1c62047a
[I 2024-06-27 14:58:16.012 ServerApp] Saving file at /Untitled8.ipynb
[W 2024-06-27 14:59:19.383 ServerApp] delete /groundtruth_eval_dataset.csv
[W 2024-06-27 14:59:22.887 ServerApp] delete /ragas_dataset.csv
[I 2024-06-27 15:00:16.362 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 15:02:17.165 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 15:04:17.769 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 15:06:18.360 ServerApp] Saving file at /Untitled8.ipynb
[W 2024-06-27 15:06:18.574 ServerApp] /home/Work/00.Work_muyu/.~Untitled8.ipynb doesn't exist
[I 2024-06-27 15:08:18.844 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 15:10:19.505 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 15:12:20.026 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 15:14:20.508 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 15:14:21.132 ServerApp] Kernel restarted: 2c70e5d8-3d38-47c7-b7af-d61c968020c6
[I 2024-06-27 15:14:21.140 ServerApp] Starting buffering for 2c70e5d8-3d38-47c7-b7af-d61c968020c6:2edc215b-4f75-485e-8d1f-631e1c62047a
[I 2024-06-27 15:14:21.147 ServerApp] Connecting to kernel 2c70e5d8-3d38-47c7-b7af-d61c968020c6.
[I 2024-06-27 15:14:21.147 ServerApp] Restoring connection for 2c70e5d8-3d38-47c7-b7af-d61c968020c6:2edc215b-4f75-485e-8d1f-631e1c62047a
[W 2024-06-27 15:14:25.313 ServerApp] delete /groundtruth_eval_dataset.csv
[W 2024-06-27 15:14:28.858 ServerApp] delete /ragas_dataset.csv
[I 2024-06-27 15:16:20.944 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 15:18:21.421 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 15:20:21.862 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 15:22:22.341 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 15:24:22.823 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 15:26:23.295 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 15:28:23.759 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 15:30:24.220 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 15:31:00.205 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 15:31:00.952 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 15:33:01.373 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 15:34:20.681 ServerApp] Starting buffering for 2c70e5d8-3d38-47c7-b7af-d61c968020c6:2edc215b-4f75-485e-8d1f-631e1c62047a
[I 2024-06-27 15:34:20.695 ServerApp] Connecting to kernel 2c70e5d8-3d38-47c7-b7af-d61c968020c6.
[I 2024-06-27 15:34:20.695 ServerApp] Restoring connection for 2c70e5d8-3d38-47c7-b7af-d61c968020c6:2edc215b-4f75-485e-8d1f-631e1c62047a
[I 2024-06-27 15:35:01.779 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 15:37:02.273 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 15:39:02.663 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 15:41:03.086 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 15:43:03.514 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 15:44:22.476 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 15:44:38.732 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 15:45:21.933 ServerApp] Saving file at /Untitled8.ipynb
[I 2024-06-27 15:45:32.211 ServerApp] Saving file at /Ragas.ipynb
[I 2024-06-27 15:54:25.666 ServerApp] Starting buffering for 5353634b-f2cf-4233-8ad5-23048f1b04f5:50339117-6338-448d-af78-7c9df2f20d1b
[I 2024-06-27 15:54:25.668 ServerApp] Starting buffering for baeb9567-5264-4d68-b010-6f45f6919e32:01f65e79-c69d-4da4-aa42-08eab3d8e979
[I 2024-06-27 15:54:25.669 ServerApp] Starting buffering for 2c70e5d8-3d38-47c7-b7af-d61c968020c6:2edc215b-4f75-485e-8d1f-631e1c62047a
[I 2024-06-27 15:54:25.671 ServerApp] Starting buffering for 67128c2d-1b0c-4581-b6af-eede01c75662:97ff236a-dbe1-4481-bb43-949a8f698a87
[I 2024-06-27 15:54:25.672 ServerApp] Starting buffering for c6d3dde6-85de-4410-98a7-bd23726ef53a:0cbb7bb0-7ab2-459d-a923-bbfa8c553139
[I 2024-06-27 15:54:25.673 ServerApp] Starting buffering for 7cf81b17-6bc1-42b1-83c2-649a94b21e38:fe275c63-b82b-4f1f-af1d-65ca823c3c70
[I 2024-06-27 16:42:16.734 ServerApp] 302 GET / (@192.168.110.91) 1.84ms
[I 2024-06-27 16:42:18.565 ServerApp] Connecting to kernel 5353634b-f2cf-4233-8ad5-23048f1b04f5.
[I 2024-06-27 16:42:18.608 ServerApp] Connecting to kernel 7cf81b17-6bc1-42b1-83c2-649a94b21e38.
[I 2024-06-27 16:42:18.682 ServerApp] Connecting to kernel 67128c2d-1b0c-4581-b6af-eede01c75662.
[I 2024-06-27 16:42:18.695 ServerApp] Starting buffering for 5353634b-f2cf-4233-8ad5-23048f1b04f5:476745e5-c5d8-449c-a791-152afbc450c2
[I 2024-06-27 16:42:18.718 ServerApp] Starting buffering for 7cf81b17-6bc1-42b1-83c2-649a94b21e38:95f8fe20-95df-4ea5-9ac7-8d1fe10369c9
[I 2024-06-27 16:42:18.720 ServerApp] Connecting to kernel baeb9567-5264-4d68-b010-6f45f6919e32.
[I 2024-06-27 16:42:18.742 ServerApp] Connecting to kernel c6d3dde6-85de-4410-98a7-bd23726ef53a.
[I 2024-06-27 16:42:18.750 ServerApp] Starting buffering for 67128c2d-1b0c-4581-b6af-eede01c75662:8a3f4ed3-20ef-4a79-8dd8-9d8e8c1e2293
[I 2024-06-27 16:42:18.775 ServerApp] Connecting to kernel 886c2b52-a9b9-442a-a6fd-52aadc363ec3.
[I 2024-06-27 16:42:18.786 ServerApp] Starting buffering for c6d3dde6-85de-4410-98a7-bd23726ef53a:56cc7fbc-531b-453f-b746-72d7c5ebc797
[I 2024-06-27 16:42:18.793 ServerApp] Connecting to kernel 2c70e5d8-3d38-47c7-b7af-d61c968020c6.
[I 2024-06-27 16:42:18.828 ServerApp] Starting buffering for baeb9567-5264-4d68-b010-6f45f6919e32:26ebc09e-ef4a-4728-8330-6a4f0abe662c
[I 2024-06-27 16:42:18.831 ServerApp] Starting buffering for 886c2b52-a9b9-442a-a6fd-52aadc363ec3:e65ca834-f6a2-40ea-8f9a-34036040ed41
[I 2024-06-27 16:42:18.884 ServerApp] Starting buffering for 2c70e5d8-3d38-47c7-b7af-d61c968020c6:d090680f-ec64-46c0-a91d-9bbb26cf99be
[W 2024-06-27 16:42:18.898 ServerApp] 404 GET /api/contents/Untitled5.ipynb?content=0&1719477745812 (192.168.110.91): No such file or directory: Untitled5.ipynb
[W 2024-06-27 16:42:18.899 ServerApp] wrote error: 'No such file or directory: Untitled5.ipynb'
    Traceback (most recent call last):
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/services/contents/handlers.py", line 121, in get
        model = await ensure_async(
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 189, in ensure_async
        result = await obj
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 863, in get
        raise web.HTTPError(404, "No such file or directory: %s" % path)
    tornado.web.HTTPError: HTTP 404: Not Found (No such file or directory: Untitled5.ipynb)
[W 2024-06-27 16:42:18.901 ServerApp] 404 GET /api/contents/Untitled5.ipynb?content=0&1719477745812 (a100870793c1426bafb8831fccd278cb@192.168.110.91) 5.01ms referer=http://192.168.110.131:8006/lab?
[W 2024-06-27 16:42:18.905 ServerApp] 404 GET /api/contents/Untitled6.ipynb?content=0&1719477745812 (192.168.110.91): No such file or directory: Untitled6.ipynb
[W 2024-06-27 16:42:18.906 ServerApp] wrote error: 'No such file or directory: Untitled6.ipynb'
    Traceback (most recent call last):
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/services/contents/handlers.py", line 121, in get
        model = await ensure_async(
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 189, in ensure_async
        result = await obj
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/services/contents/filemanager.py", line 863, in get
        raise web.HTTPError(404, "No such file or directory: %s" % path)
    tornado.web.HTTPError: HTTP 404: Not Found (No such file or directory: Untitled6.ipynb)
[W 2024-06-27 16:42:18.906 ServerApp] 404 GET /api/contents/Untitled6.ipynb?content=0&1719477745812 (a100870793c1426bafb8831fccd278cb@192.168.110.91) 4.01ms referer=http://192.168.110.131:8006/lab?
[I 2024-06-27 16:42:19.037 LabApp] Build is up to date
[I 2024-06-27 16:42:19.412 ServerApp] Kernel started: 303a2f81-143b-4852-931d-29522c7e2543
[I 2024-06-27 16:42:19.417 ServerApp] Kernel started: 79d5baed-0cbf-4566-9ff2-102a89cdeaee
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
[I 2024-06-27 16:42:22.376 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), new random ports
[I 2024-06-27 16:42:22.392 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), new random ports
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
[I 2024-06-27 16:42:25.391 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (2/5), new random ports
[I 2024-06-27 16:42:25.408 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (2/5), new random ports
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
[I 2024-06-27 16:42:28.408 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (3/5), new random ports
[I 2024-06-27 16:42:28.424 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (3/5), new random ports
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
[I 2024-06-27 16:42:31.424 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (4/5), new random ports
[I 2024-06-27 16:42:31.441 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (4/5), new random ports
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
[I 2024-06-27 16:42:34.441 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (5/5), new random ports
[I 2024-06-27 16:42:34.457 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (5/5), new random ports
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
[W 2024-06-27 16:42:37.458 ServerApp] AsyncIOLoopKernelRestarter: restart failed
[W 2024-06-27 16:42:37.458 ServerApp] Kernel 303a2f81-143b-4852-931d-29522c7e2543 died, removing from map.
[W 2024-06-27 16:42:37.473 ServerApp] AsyncIOLoopKernelRestarter: restart failed
[W 2024-06-27 16:42:37.473 ServerApp] Kernel 79d5baed-0cbf-4566-9ff2-102a89cdeaee died, removing from map.
[I 2024-06-27 16:42:44.816 ServerApp] Connecting to kernel 2c70e5d8-3d38-47c7-b7af-d61c968020c6.
[I 2024-06-27 16:43:11.288 ServerApp] Creating new notebook in 
[I 2024-06-27 16:43:11.436 ServerApp] Kernel started: 9294e268-f18e-428d-80d5-649a51de8fd0
[I 2024-06-27 16:43:12.035 ServerApp] Connecting to kernel 9294e268-f18e-428d-80d5-649a51de8fd0.
[I 2024-06-27 16:43:13.659 ServerApp] Starting buffering for 9294e268-f18e-428d-80d5-649a51de8fd0:e26b3897-bcd2-4465-86fe-436897e21d1e
[I 2024-06-27 16:43:17.189 ServerApp] Kernel shutdown: 9294e268-f18e-428d-80d5-649a51de8fd0
[W 2024-06-27 16:43:17.522 ServerApp] delete /Untitled.ipynb
[E 2024-06-27 16:43:19.490 ServerApp] Uncaught exception GET /api/kernels/79d5baed-0cbf-4566-9ff2-102a89cdeaee/channels?session_id=da29fbc6-a2f6-4c74-9893-b765d94f04fe (192.168.110.91)
    HTTPServerRequest(protocol='http', host='192.168.110.131:8006', method='GET', uri='/api/kernels/79d5baed-0cbf-4566-9ff2-102a89cdeaee/channels?session_id=da29fbc6-a2f6-4c74-9893-b765d94f04fe', version='HTTP/1.1', remote_ip='192.168.110.91')
    Traceback (most recent call last):
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/services/kernels/websocket.py", line 64, in get
        await self.pre_get()
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/services/kernels/websocket.py", line 59, in pre_get
        await self.connection.prepare()
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/services/kernels/connection/channels.py", line 317, in prepare
        raise TimeoutError(msg)
    TimeoutError: Kernel never reached an 'alive' state.
[E 2024-06-27 16:43:19.493 ServerApp] {
      "Host": "192.168.110.131:8006",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
    }
[E 2024-06-27 16:43:19.493 ServerApp] 500 GET /api/kernels/79d5baed-0cbf-4566-9ff2-102a89cdeaee/channels?session_id=da29fbc6-a2f6-4c74-9893-b765d94f04fe (a100870793c1426bafb8831fccd278cb@192.168.110.91) 60049.73ms referer=None
[I 2024-06-27 16:44:31.819 ServerApp] Kernel restarted: 2c70e5d8-3d38-47c7-b7af-d61c968020c6
[I 2024-06-27 16:44:31.826 ServerApp] Starting buffering for 2c70e5d8-3d38-47c7-b7af-d61c968020c6:27802241-2310-4594-afa1-9e985a8a4bba
[I 2024-06-27 16:44:31.835 ServerApp] Connecting to kernel 2c70e5d8-3d38-47c7-b7af-d61c968020c6.
[I 2024-06-27 16:44:31.836 ServerApp] Restoring connection for 2c70e5d8-3d38-47c7-b7af-d61c968020c6:27802241-2310-4594-afa1-9e985a8a4bba
[W 2024-06-27 16:44:45.007 ServerApp] delete /groundtruth_eval_dataset.csv
[W 2024-06-27 16:44:48.050 ServerApp] delete /ragas_dataset.csv
[I 2024-06-27 16:46:19.655 ServerApp] Saving file at /Ragas.ipynb
[I 2024-06-27 16:48:20.045 ServerApp] Saving file at /Ragas.ipynb
[I 2024-06-27 16:50:20.439 ServerApp] Saving file at /Ragas.ipynb
[I 2024-06-27 16:54:20.885 ServerApp] Saving file at /Ragas.ipynb
[I 2024-06-27 16:56:21.262 ServerApp] Saving file at /Ragas.ipynb
[I 2024-06-27 16:58:21.665 ServerApp] Saving file at /Ragas.ipynb
[I 2024-06-27 17:00:22.053 ServerApp] Saving file at /Ragas.ipynb
[I 2024-06-27 17:02:22.448 ServerApp] Saving file at /Ragas.ipynb
[I 2024-06-27 17:04:22.849 ServerApp] Saving file at /Ragas.ipynb
[I 2024-06-27 17:06:23.460 ServerApp] Saving file at /Ragas.ipynb
[I 2024-06-27 17:08:24.037 ServerApp] Saving file at /Ragas.ipynb
[I 2024-06-27 17:10:07.048 ServerApp] Saving file at /Ragas.ipynb
[I 2024-06-27 17:10:07.828 ServerApp] Saving file at /Ragas.ipynb
[W 2024-06-27 18:27:13.414 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-06-27 18:27:13.418 ServerApp] 403 GET /api/kernelspecs?1719484040138 (@192.168.110.91) 8.52ms referer=http://192.168.110.131:8006/lab/tree/Ragas.ipynb
[W 2024-06-27 18:27:13.424 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-06-27 18:27:13.425 ServerApp] 403 GET /api/me?1719484040138 (@192.168.110.91) 5.35ms referer=http://192.168.110.131:8006/lab/tree/Ragas.ipynb
[W 2024-06-27 18:27:13.426 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-06-27 18:27:13.426 ServerApp] 403 GET /api/kernels?1719484040139 (@192.168.110.91) 6.10ms referer=http://192.168.110.131:8006/lab/tree/Ragas.ipynb
[W 2024-06-27 18:27:13.428 TerminalsExtensionApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-06-27 18:27:13.428 TerminalsExtensionApp] 403 GET /api/terminals?1719484040139 (@192.168.110.91) 7.34ms referer=http://192.168.110.131:8006/lab/tree/Ragas.ipynb
[W 2024-06-27 18:27:13.429 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-06-27 18:27:13.430 ServerApp] 403 GET /api/sessions?1719484040139 (@192.168.110.91) 8.23ms referer=http://192.168.110.131:8006/lab/tree/Ragas.ipynb
[W 2024-06-27 18:27:13.431 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-06-27 18:27:13.432 ServerApp] 403 GET /api/contents?content=1&1719484040139 (@192.168.110.91) 9.04ms referer=http://192.168.110.131:8006/lab/tree/Ragas.ipynb
[W 2024-06-27 18:27:16.625 ServerApp] 403 PUT /lab/api/workspaces/default?1719484043398 (192.168.110.91): '_xsrf' argument missing from POST
[W 2024-06-27 18:27:16.626 LabApp] wrote error: "'_xsrf' argument missing from POST"
    Traceback (most recent call last):
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 1765, in _execute
        result = await result  # type: ignore
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 731, in prepare
        await super().prepare()
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 632, in prepare
        self.check_xsrf_cookie()
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 536, in check_xsrf_cookie
        return super().check_xsrf_cookie()
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 1601, in check_xsrf_cookie
        raise HTTPError(403, "'_xsrf' argument missing from POST")
    tornado.web.HTTPError: HTTP 403: Forbidden ('_xsrf' argument missing from POST)
[W 2024-06-27 18:27:16.627 LabApp] 403 PUT /lab/api/workspaces/default?1719484043398 (@192.168.110.91) 2.77ms referer=http://192.168.110.131:8006/lab/tree/Ragas.ipynb
[W 2024-06-27 18:27:17.599 ServerApp] 403 PUT /lab/api/workspaces/default?1719484044376 (192.168.110.91): '_xsrf' argument missing from POST
[W 2024-06-27 18:27:17.599 LabApp] wrote error: "'_xsrf' argument missing from POST"
    Traceback (most recent call last):
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 1765, in _execute
        result = await result  # type: ignore
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 731, in prepare
        await super().prepare()
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 632, in prepare
        self.check_xsrf_cookie()
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 536, in check_xsrf_cookie
        return super().check_xsrf_cookie()
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 1601, in check_xsrf_cookie
        raise HTTPError(403, "'_xsrf' argument missing from POST")
    tornado.web.HTTPError: HTTP 403: Forbidden ('_xsrf' argument missing from POST)
[W 2024-06-27 18:27:17.600 LabApp] 403 PUT /lab/api/workspaces/default?1719484044376 (@192.168.110.91) 2.27ms referer=http://192.168.110.131:8006/lab/tree/Ragas.ipynb
[W 2024-06-27 18:27:18.555 ServerApp] 403 PUT /lab/api/workspaces/default?1719484045330 (192.168.110.91): '_xsrf' argument missing from POST
[W 2024-06-27 18:27:18.555 LabApp] wrote error: "'_xsrf' argument missing from POST"
    Traceback (most recent call last):
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 1765, in _execute
        result = await result  # type: ignore
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 731, in prepare
        await super().prepare()
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 632, in prepare
        self.check_xsrf_cookie()
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 536, in check_xsrf_cookie
        return super().check_xsrf_cookie()
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 1601, in check_xsrf_cookie
        raise HTTPError(403, "'_xsrf' argument missing from POST")
    tornado.web.HTTPError: HTTP 403: Forbidden ('_xsrf' argument missing from POST)
[W 2024-06-27 18:27:18.556 LabApp] 403 PUT /lab/api/workspaces/default?1719484045330 (@192.168.110.91) 2.14ms referer=http://192.168.110.131:8006/lab/tree/Ragas.ipynb
[W 2024-06-27 18:27:23.440 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-06-27 18:27:23.442 ServerApp] 403 GET /api/contents?content=1&1719484050218 (@192.168.110.91) 2.00ms referer=http://192.168.110.131:8006/lab/tree/Ragas.ipynb
[W 2024-06-27 18:27:25.960 ServerApp] 403 PUT /lab/api/settings/@jupyterlab/apputils-extension:themes?1719484052732 (192.168.110.91): '_xsrf' argument missing from POST
[W 2024-06-27 18:27:25.960 LabApp] wrote error: "'_xsrf' argument missing from POST"
    Traceback (most recent call last):
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 1765, in _execute
        result = await result  # type: ignore
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 731, in prepare
        await super().prepare()
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 632, in prepare
        self.check_xsrf_cookie()
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 536, in check_xsrf_cookie
        return super().check_xsrf_cookie()
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 1601, in check_xsrf_cookie
        raise HTTPError(403, "'_xsrf' argument missing from POST")
    tornado.web.HTTPError: HTTP 403: Forbidden ('_xsrf' argument missing from POST)
[W 2024-06-27 18:27:25.961 LabApp] 403 PUT /lab/api/settings/@jupyterlab/apputils-extension:themes?1719484052732 (@192.168.110.91) 7.18ms referer=http://192.168.110.131:8006/lab/tree/Ragas.ipynb
[W 2024-06-27 18:27:27.231 TerminalsExtensionApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-06-27 18:27:27.232 TerminalsExtensionApp] 403 GET /api/terminals?1719484054006 (@192.168.110.91) 1.84ms referer=http://192.168.110.131:8006/lab/tree/Ragas.ipynb
[W 2024-06-27 18:27:28.505 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-06-27 18:27:28.507 ServerApp] 403 GET /api/kernels?1719484055274 (@192.168.110.91) 2.32ms referer=http://192.168.110.131:8006/lab/tree/Ragas.ipynb
[W 2024-06-27 18:27:30.632 ServerApp] 403 PUT /lab/api/settings/@jupyterlab/apputils-extension:themes?1719484057405 (192.168.110.91): '_xsrf' argument missing from POST
[W 2024-06-27 18:27:30.632 LabApp] wrote error: "'_xsrf' argument missing from POST"
    Traceback (most recent call last):
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 1765, in _execute
        result = await result  # type: ignore
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 731, in prepare
        await super().prepare()
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 632, in prepare
        self.check_xsrf_cookie()
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 536, in check_xsrf_cookie
        return super().check_xsrf_cookie()
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 1601, in check_xsrf_cookie
        raise HTTPError(403, "'_xsrf' argument missing from POST")
    tornado.web.HTTPError: HTTP 403: Forbidden ('_xsrf' argument missing from POST)
[W 2024-06-27 18:27:30.633 LabApp] 403 PUT /lab/api/settings/@jupyterlab/apputils-extension:themes?1719484057405 (@192.168.110.91) 4.81ms referer=http://192.168.110.131:8006/lab/tree/Ragas.ipynb
[W 2024-06-27 18:27:33.454 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-06-27 18:27:33.455 ServerApp] 403 GET /api/contents?content=1&1719484060226 (@192.168.110.91) 1.91ms referer=http://192.168.110.131:8006/lab/tree/Ragas.ipynb
[I 2024-06-27 18:27:33.856 LabApp] 302 GET /lab/tree/Ragas.ipynb (@192.168.110.91) 1.21ms
[I 2024-06-27 18:27:33.877 ServerApp] Starting buffering for 2c70e5d8-3d38-47c7-b7af-d61c968020c6:27802241-2310-4594-afa1-9e985a8a4bba
[W 2024-06-27 18:27:38.597 ServerApp] 401 POST /login?next=%2Flab%2Ftree%2FRagas.ipynb (@192.168.110.91) 51.85ms referer=http://192.168.110.131:8006/login?next=%2Flab%2Ftree%2FRagas.ipynb
[W 2024-06-27 18:27:43.767 ServerApp] 401 POST /login?next=%2Flab%2Ftree%2FRagas.ipynb (@192.168.110.91) 48.03ms referer=http://192.168.110.131:8006/login?next=%2Flab%2Ftree%2FRagas.ipynb
[I 2024-06-27 18:28:37.405 ServerApp] User bbf9201741c3491bbc43584817a64c40 logged in.
[I 2024-06-27 18:28:37.407 ServerApp] 302 POST /login?next=%2Flab%2Ftree%2FRagas.ipynb (bbf9201741c3491bbc43584817a64c40@192.168.110.91) 48.96ms
[I 2024-06-27 18:28:40.521 ServerApp] Connecting to kernel 67128c2d-1b0c-4581-b6af-eede01c75662.
[I 2024-06-27 18:28:40.527 ServerApp] Connecting to kernel baeb9567-5264-4d68-b010-6f45f6919e32.
[I 2024-06-27 18:28:40.531 ServerApp] Connecting to kernel c6d3dde6-85de-4410-98a7-bd23726ef53a.
[I 2024-06-27 18:28:40.535 ServerApp] Connecting to kernel 886c2b52-a9b9-442a-a6fd-52aadc363ec3.
[I 2024-06-27 18:28:40.539 ServerApp] Connecting to kernel 5353634b-f2cf-4233-8ad5-23048f1b04f5.
[I 2024-06-27 18:28:40.542 ServerApp] Connecting to kernel 7cf81b17-6bc1-42b1-83c2-649a94b21e38.
[I 2024-06-27 18:28:40.547 ServerApp] Connecting to kernel 2c70e5d8-3d38-47c7-b7af-d61c968020c6.
[I 2024-06-27 18:28:40.689 ServerApp] Starting buffering for 67128c2d-1b0c-4581-b6af-eede01c75662:38b36f9b-12d0-4196-8a37-ae64e088f53a
[I 2024-06-27 18:28:40.690 ServerApp] Starting buffering for 886c2b52-a9b9-442a-a6fd-52aadc363ec3:d356e267-60fa-4483-87ba-88689af4f13f
[I 2024-06-27 18:28:40.691 ServerApp] Starting buffering for baeb9567-5264-4d68-b010-6f45f6919e32:43cc185d-b55c-427b-a572-2b4b1d0d7332
[I 2024-06-27 18:28:40.691 ServerApp] Starting buffering for 7cf81b17-6bc1-42b1-83c2-649a94b21e38:e8c99777-ebbe-463d-a98f-2493aa7fc006
[I 2024-06-27 18:28:40.692 ServerApp] Starting buffering for 2c70e5d8-3d38-47c7-b7af-d61c968020c6:30affde5-ba53-4f2b-b33e-ff86277eecac
[I 2024-06-27 18:28:40.694 ServerApp] Starting buffering for c6d3dde6-85de-4410-98a7-bd23726ef53a:0284102b-2de2-4587-b438-4dad39cd3305
[I 2024-06-27 18:28:40.695 ServerApp] Starting buffering for 5353634b-f2cf-4233-8ad5-23048f1b04f5:4f5b32af-e0cf-4c7d-b211-1d248b6df4b8
[I 2024-06-27 18:28:40.957 LabApp] Build is up to date
[I 2024-06-27 18:28:41.285 ServerApp] Kernel started: 926be4e5-9b1c-4a7b-a0e9-305880abf53d
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
[W 2024-06-27 18:28:41.512 ServerApp] 404 PATCH http://192.168.110.131:8006/api/sessions/d3b97a47-c93c-4cc5-b8b3-1acb9b89e342?1719484128253 (bbf9201741c3491bbc43584817a64c40@192.168.110.91) 29.25ms referer=http://192.168.110.131:8006/lab/tree/Ragas.ipynb
[I 2024-06-27 18:28:41.515 ServerApp] Connecting to kernel 2c70e5d8-3d38-47c7-b7af-d61c968020c6.
[I 2024-06-27 18:28:44.263 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), new random ports
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
[I 2024-06-27 18:28:47.280 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (2/5), new random ports
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
[I 2024-06-27 18:28:55.936 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (3/5), new random ports
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
[I 2024-06-27 18:28:58.954 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (4/5), new random ports
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
[I 2024-06-27 18:28:59.954 ServerApp] Kernel started: f4a02b03-8091-4354-bd72-e7288ad790f5
[W 2024-06-27 18:28:59.977 ServerApp] 404 PATCH http://192.168.110.131:8006/api/sessions/88e9606c-304a-4a5b-bb1b-509d535954a9?1719484146752 (bbf9201741c3491bbc43584817a64c40@192.168.110.91) 2.79ms referer=http://192.168.110.131:8006/lab/tree/Ragas.ipynb
[I 2024-06-27 18:29:00.498 ServerApp] Connecting to kernel f4a02b03-8091-4354-bd72-e7288ad790f5.
[I 2024-06-27 18:29:01.970 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (5/5), new random ports
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
[W 2024-06-27 18:29:04.988 ServerApp] AsyncIOLoopKernelRestarter: restart failed
[W 2024-06-27 18:29:04.988 ServerApp] Kernel 926be4e5-9b1c-4a7b-a0e9-305880abf53d died, removing from map.
[W 2024-06-27 18:29:44.309 ServerApp] Timeout waiting for kernel_info reply from 926be4e5-9b1c-4a7b-a0e9-305880abf53d
[E 2024-06-27 18:29:44.310 ServerApp] Uncaught exception GET /api/kernels/926be4e5-9b1c-4a7b-a0e9-305880abf53d/channels?session_id=1cb8e7dc-7830-459f-a348-1984c6dd7ce5 (192.168.110.91)
    HTTPServerRequest(protocol='http', host='192.168.110.131:8006', method='GET', uri='/api/kernels/926be4e5-9b1c-4a7b-a0e9-305880abf53d/channels?session_id=1cb8e7dc-7830-459f-a348-1984c6dd7ce5', version='HTTP/1.1', remote_ip='192.168.110.91')
    Traceback (most recent call last):
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/services/kernels/websocket.py", line 65, in get
        await super().get(kernel_id=kernel_id)
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/websocket.py", line 272, in get
        await self.ws_connection.accept_connection(self)
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/websocket.py", line 862, in accept_connection
        await self._accept_connection(handler)
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/websocket.py", line 902, in _accept_connection
        self.selected_subprotocol = handler.select_subprotocol(subprotocols)
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/services/kernels/websocket.py", line 87, in select_subprotocol
        preferred_protocol = self.connection.kernel_ws_protocol
    AttributeError: 'NoneType' object has no attribute 'kernel_ws_protocol'
[E 2024-06-27 18:29:44.313 ServerApp] {
      "Host": "192.168.110.131:8006",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
    }
[E 2024-06-27 18:29:44.314 ServerApp] 500 GET /api/kernels/926be4e5-9b1c-4a7b-a0e9-305880abf53d/channels?session_id=1cb8e7dc-7830-459f-a348-1984c6dd7ce5 (bbf9201741c3491bbc43584817a64c40@192.168.110.91) 62841.19ms referer=None
[W 2024-06-27 18:29:52.943 ServerApp] Timeout waiting for kernel_info reply from 926be4e5-9b1c-4a7b-a0e9-305880abf53d
[E 2024-06-27 18:29:52.944 ServerApp] Uncaught exception GET /api/kernels/926be4e5-9b1c-4a7b-a0e9-305880abf53d/channels?session_id=fd2511f1-38f5-4433-b24c-784bc812dc89 (192.168.110.91)
    HTTPServerRequest(protocol='http', host='192.168.110.131:8006', method='GET', uri='/api/kernels/926be4e5-9b1c-4a7b-a0e9-305880abf53d/channels?session_id=fd2511f1-38f5-4433-b24c-784bc812dc89', version='HTTP/1.1', remote_ip='192.168.110.91')
    Traceback (most recent call last):
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/services/kernels/websocket.py", line 65, in get
        await super().get(kernel_id=kernel_id)
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/websocket.py", line 272, in get
        await self.ws_connection.accept_connection(self)
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/websocket.py", line 862, in accept_connection
        await self._accept_connection(handler)
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/websocket.py", line 902, in _accept_connection
        self.selected_subprotocol = handler.select_subprotocol(subprotocols)
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/services/kernels/websocket.py", line 87, in select_subprotocol
        preferred_protocol = self.connection.kernel_ws_protocol
    AttributeError: 'NoneType' object has no attribute 'kernel_ws_protocol'
[E 2024-06-27 18:29:52.947 ServerApp] {
      "Host": "192.168.110.131:8006",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
    }
[E 2024-06-27 18:29:52.947 ServerApp] 500 GET /api/kernels/926be4e5-9b1c-4a7b-a0e9-305880abf53d/channels?session_id=fd2511f1-38f5-4433-b24c-784bc812dc89 (bbf9201741c3491bbc43584817a64c40@192.168.110.91) 71468.26ms referer=None
[I 2024-06-27 18:31:54.736 ServerApp] Starting buffering for 2c70e5d8-3d38-47c7-b7af-d61c968020c6:df5e79b7-7cc6-4979-83db-49c45371770f
[I 2024-06-27 18:31:54.738 ServerApp] Starting buffering for f4a02b03-8091-4354-bd72-e7288ad790f5:9ec94bd5-ad26-4a08-b0b7-69feab67256a
[I 2024-06-27 18:31:55.547 ServerApp] Connecting to kernel f4a02b03-8091-4354-bd72-e7288ad790f5.
[I 2024-06-27 18:31:55.548 ServerApp] Restoring connection for f4a02b03-8091-4354-bd72-e7288ad790f5:9ec94bd5-ad26-4a08-b0b7-69feab67256a
[I 2024-06-27 18:31:56.543 ServerApp] Connecting to kernel 2c70e5d8-3d38-47c7-b7af-d61c968020c6.
[I 2024-06-27 18:31:56.543 ServerApp] Restoring connection for 2c70e5d8-3d38-47c7-b7af-d61c968020c6:df5e79b7-7cc6-4979-83db-49c45371770f
[I 2024-06-27 20:44:10.677 ServerApp] Kernel restarted: 2c70e5d8-3d38-47c7-b7af-d61c968020c6
[I 2024-06-27 20:44:10.685 ServerApp] Starting buffering for 2c70e5d8-3d38-47c7-b7af-d61c968020c6:df5e79b7-7cc6-4979-83db-49c45371770f
[I 2024-06-27 20:44:10.692 ServerApp] Connecting to kernel 2c70e5d8-3d38-47c7-b7af-d61c968020c6.
[I 2024-06-27 20:44:10.692 ServerApp] Restoring connection for 2c70e5d8-3d38-47c7-b7af-d61c968020c6:df5e79b7-7cc6-4979-83db-49c45371770f
[I 2024-06-27 20:44:55.924 ServerApp] Saving file at /Ragas.ipynb
[I 2024-06-27 20:46:56.329 ServerApp] Saving file at /Ragas.ipynb
[I 2024-06-27 20:48:56.712 ServerApp] Saving file at /Ragas.ipynb
[I 2024-06-27 20:50:57.145 ServerApp] Saving file at /Ragas.ipynb
[I 2024-06-27 20:52:57.577 ServerApp] Saving file at /Ragas.ipynb
[I 2024-06-27 20:54:57.985 ServerApp] Saving file at /Ragas.ipynb
[I 2024-06-27 20:56:58.407 ServerApp] Saving file at /Ragas.ipynb
[I 2024-06-27 20:58:58.867 ServerApp] Saving file at /Ragas.ipynb
[I 2024-06-27 21:00:59.254 ServerApp] Saving file at /Ragas.ipynb
[I 2024-06-27 21:02:59.667 ServerApp] Saving file at /Ragas.ipynb
[I 2024-06-27 21:05:00.043 ServerApp] Saving file at /Ragas.ipynb
[I 2024-06-27 21:07:00.454 ServerApp] Saving file at /Ragas.ipynb
[W 2024-06-27 21:08:04.801 ServerApp] delete /groundtruth_eval_dataset.csv
[W 2024-06-27 21:08:10.192 ServerApp] delete /ragas_dataset.csv
[I 2024-06-27 21:09:00.875 ServerApp] Saving file at /Ragas.ipynb
[I 2024-06-27 21:11:01.965 ServerApp] Saving file at /Ragas.ipynb
[I 2024-06-27 21:13:02.960 ServerApp] Saving file at /Ragas.ipynb
[I 2024-06-27 21:17:03.412 ServerApp] Saving file at /Ragas.ipynb
[I 2024-06-27 21:19:03.828 ServerApp] Saving file at /Ragas.ipynb
[I 2024-06-27 21:21:04.259 ServerApp] Saving file at /Ragas.ipynb
[I 2024-06-27 21:23:04.674 ServerApp] Saving file at /Ragas.ipynb
[I 2024-06-27 21:32:49.105 ServerApp] Starting buffering for 2c70e5d8-3d38-47c7-b7af-d61c968020c6:df5e79b7-7cc6-4979-83db-49c45371770f
[I 2024-06-27 21:32:49.107 ServerApp] Starting buffering for f4a02b03-8091-4354-bd72-e7288ad790f5:9ec94bd5-ad26-4a08-b0b7-69feab67256a
[I 2024-06-28 15:00:34.848 ServerApp] Connecting to kernel 7cf81b17-6bc1-42b1-83c2-649a94b21e38.
[I 2024-06-28 15:00:34.854 ServerApp] Connecting to kernel 5353634b-f2cf-4233-8ad5-23048f1b04f5.
[I 2024-06-28 15:00:34.860 ServerApp] Connecting to kernel 67128c2d-1b0c-4581-b6af-eede01c75662.
[I 2024-06-28 15:00:34.863 ServerApp] Connecting to kernel c6d3dde6-85de-4410-98a7-bd23726ef53a.
[I 2024-06-28 15:00:34.867 ServerApp] Connecting to kernel baeb9567-5264-4d68-b010-6f45f6919e32.
[I 2024-06-28 15:00:34.871 ServerApp] Connecting to kernel 886c2b52-a9b9-442a-a6fd-52aadc363ec3.
[I 2024-06-28 15:00:34.914 ServerApp] Connecting to kernel 2c70e5d8-3d38-47c7-b7af-d61c968020c6.
[I 2024-06-28 15:00:34.917 ServerApp] Connecting to kernel f4a02b03-8091-4354-bd72-e7288ad790f5.
[I 2024-06-28 15:00:35.032 ServerApp] Starting buffering for baeb9567-5264-4d68-b010-6f45f6919e32:b9065b2e-108f-44c7-82b9-2f7427b3bbd7
[I 2024-06-28 15:00:35.033 ServerApp] Starting buffering for 5353634b-f2cf-4233-8ad5-23048f1b04f5:aa136cd9-df7a-4e07-a4cc-f946245a0911
[I 2024-06-28 15:00:35.035 ServerApp] Starting buffering for 886c2b52-a9b9-442a-a6fd-52aadc363ec3:2c96bd21-5897-4828-a090-5abab1fea51a
[I 2024-06-28 15:00:35.035 ServerApp] Starting buffering for 7cf81b17-6bc1-42b1-83c2-649a94b21e38:f7d1827a-0fa8-45c7-80ec-c2aea666c262
[I 2024-06-28 15:00:35.037 ServerApp] Starting buffering for c6d3dde6-85de-4410-98a7-bd23726ef53a:2f337d27-53c8-4e08-8661-2d3c987fbbfe
[I 2024-06-28 15:00:35.037 ServerApp] Starting buffering for 67128c2d-1b0c-4581-b6af-eede01c75662:697cbc05-5f84-4c05-bc3e-4509098c1aaa
[I 2024-06-28 15:00:35.043 ServerApp] Starting buffering for 2c70e5d8-3d38-47c7-b7af-d61c968020c6:7ade405b-73f3-44e1-b5ea-538abbee3bf0
[I 2024-06-28 15:00:35.082 ServerApp] Starting buffering for f4a02b03-8091-4354-bd72-e7288ad790f5:1cabc16e-885e-48b5-b890-f06b73e359fe
[I 2024-06-28 15:00:35.446 LabApp] Build is up to date
[I 2024-06-28 15:00:35.531 ServerApp] Kernel started: 76f19b63-028b-4890-80dd-ba95d18ed249
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
[W 2024-06-28 15:00:35.684 ServerApp] 404 PATCH http://192.168.110.131:8006/api/sessions/47d8b220-ff27-4d56-8982-8a2eff69dfe1?1719558041111 (bbf9201741c3491bbc43584817a64c40@192.168.110.91) 2.50ms referer=http://192.168.110.131:8006/lab/tree/Ragas.ipynb
[I 2024-06-28 15:00:35.808 ServerApp] Connecting to kernel 2c70e5d8-3d38-47c7-b7af-d61c968020c6.
[I 2024-06-28 15:00:38.510 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), new random ports
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
[I 2024-06-28 15:00:41.461 ServerApp] Starting buffering for 2c70e5d8-3d38-47c7-b7af-d61c968020c6:2665b599-a43b-4085-bd4b-30309a346d45
[I 2024-06-28 15:00:41.526 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (2/5), new random ports
[I 2024-06-28 15:00:47.438 ServerApp] Kernel started: 18ee5317-6787-467c-a704-0f786157e6ce
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[I 2024-06-28 15:00:48.112 ServerApp] Connecting to kernel 18ee5317-6787-467c-a704-0f786157e6ce.
[I 2024-06-28 15:00:48.357 ServerApp] Connecting to kernel 2c70e5d8-3d38-47c7-b7af-d61c968020c6.
[I 2024-06-28 15:00:48.357 ServerApp] Restoring connection for 2c70e5d8-3d38-47c7-b7af-d61c968020c6:2665b599-a43b-4085-bd4b-30309a346d45
[I 2024-06-28 15:00:50.387 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (3/5), new random ports
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
[I 2024-06-28 15:00:51.338 ServerApp] Starting buffering for 2c70e5d8-3d38-47c7-b7af-d61c968020c6:2665b599-a43b-4085-bd4b-30309a346d45
[I 2024-06-28 15:00:53.297 ServerApp] Creating new notebook in 
[I 2024-06-28 15:00:53.406 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (4/5), new random ports
[I 2024-06-28 15:00:53.450 ServerApp] Kernel started: 02041086-ee0e-47f7-9229-4dcd2d52d073
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
[I 2024-06-28 15:00:56.435 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (5/5), new random ports
/home/util/anaconda3/envs/chatglm3/bin/python: No module named ipykernel_launcher
[W 2024-06-28 15:00:59.452 ServerApp] AsyncIOLoopKernelRestarter: restart failed
[W 2024-06-28 15:00:59.452 ServerApp] Kernel 76f19b63-028b-4890-80dd-ba95d18ed249 died, removing from map.
[W 2024-06-28 15:01:00.631 ServerApp] 404 GET /api/kernels/76f19b63-028b-4890-80dd-ba95d18ed249?1719558066060 (192.168.110.91): Kernel does not exist: 76f19b63-028b-4890-80dd-ba95d18ed249
[W 2024-06-28 15:01:00.631 ServerApp] wrote error: 'Kernel does not exist: 76f19b63-028b-4890-80dd-ba95d18ed249'
    Traceback (most recent call last):
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 500, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 531, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: 76f19b63-028b-4890-80dd-ba95d18ed249)
[W 2024-06-28 15:01:00.643 ServerApp] 404 GET /api/kernels/76f19b63-028b-4890-80dd-ba95d18ed249?1719558066060 (bbf9201741c3491bbc43584817a64c40@192.168.110.91) 13.05ms referer=http://192.168.110.131:8006/lab/tree/Untitled.ipynb
[I 2024-06-28 15:01:03.546 ServerApp] Connecting to kernel 02041086-ee0e-47f7-9229-4dcd2d52d073.
[W 2024-06-28 15:01:38.567 ServerApp] Timeout waiting for kernel_info reply from 76f19b63-028b-4890-80dd-ba95d18ed249
[W 2024-06-28 15:01:38.567 ServerApp] Timeout waiting for kernel_info reply from 76f19b63-028b-4890-80dd-ba95d18ed249
[E 2024-06-28 15:01:38.568 ServerApp] Uncaught exception GET /api/kernels/76f19b63-028b-4890-80dd-ba95d18ed249/channels?session_id=c83ea599-dbfe-47a2-a6aa-162a08ad8d8c (192.168.110.91)
    HTTPServerRequest(protocol='http', host='192.168.110.131:8006', method='GET', uri='/api/kernels/76f19b63-028b-4890-80dd-ba95d18ed249/channels?session_id=c83ea599-dbfe-47a2-a6aa-162a08ad8d8c', version='HTTP/1.1', remote_ip='192.168.110.91')
    Traceback (most recent call last):
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/services/kernels/websocket.py", line 65, in get
        await super().get(kernel_id=kernel_id)
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/websocket.py", line 272, in get
        await self.ws_connection.accept_connection(self)
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/websocket.py", line 862, in accept_connection
        await self._accept_connection(handler)
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/websocket.py", line 902, in _accept_connection
        self.selected_subprotocol = handler.select_subprotocol(subprotocols)
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/services/kernels/websocket.py", line 87, in select_subprotocol
        preferred_protocol = self.connection.kernel_ws_protocol
    AttributeError: 'NoneType' object has no attribute 'kernel_ws_protocol'
[E 2024-06-28 15:01:38.571 ServerApp] {
      "Host": "192.168.110.131:8006",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
    }
[E 2024-06-28 15:01:38.572 ServerApp] 500 GET /api/kernels/76f19b63-028b-4890-80dd-ba95d18ed249/channels?session_id=c83ea599-dbfe-47a2-a6aa-162a08ad8d8c (bbf9201741c3491bbc43584817a64c40@192.168.110.91) 62884.38ms referer=None
[E 2024-06-28 15:01:38.572 ServerApp] Uncaught exception GET /api/kernels/76f19b63-028b-4890-80dd-ba95d18ed249/channels?session_id=c4dda5f2-a55f-494a-8692-492f3529b7cb (192.168.110.91)
    HTTPServerRequest(protocol='http', host='192.168.110.131:8006', method='GET', uri='/api/kernels/76f19b63-028b-4890-80dd-ba95d18ed249/channels?session_id=c4dda5f2-a55f-494a-8692-492f3529b7cb', version='HTTP/1.1', remote_ip='192.168.110.91')
    Traceback (most recent call last):
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/services/kernels/websocket.py", line 65, in get
        await super().get(kernel_id=kernel_id)
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/websocket.py", line 272, in get
        await self.ws_connection.accept_connection(self)
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/websocket.py", line 862, in accept_connection
        await self._accept_connection(handler)
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/websocket.py", line 902, in _accept_connection
        self.selected_subprotocol = handler.select_subprotocol(subprotocols)
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/services/kernels/websocket.py", line 87, in select_subprotocol
        preferred_protocol = self.connection.kernel_ws_protocol
    AttributeError: 'NoneType' object has no attribute 'kernel_ws_protocol'
[E 2024-06-28 15:01:38.576 ServerApp] {
      "Host": "192.168.110.131:8006",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
    }
[E 2024-06-28 15:01:38.576 ServerApp] 500 GET /api/kernels/76f19b63-028b-4890-80dd-ba95d18ed249/channels?session_id=c4dda5f2-a55f-494a-8692-492f3529b7cb (bbf9201741c3491bbc43584817a64c40@192.168.110.91) 62888.21ms referer=None
[W 2024-06-28 15:01:53.437 ServerApp] Timeout waiting for kernel_info reply from 76f19b63-028b-4890-80dd-ba95d18ed249
[E 2024-06-28 15:01:53.437 ServerApp] Uncaught exception GET /api/kernels/76f19b63-028b-4890-80dd-ba95d18ed249/channels?session_id=c83ea599-dbfe-47a2-a6aa-162a08ad8d8c (192.168.110.91)
    HTTPServerRequest(protocol='http', host='192.168.110.131:8006', method='GET', uri='/api/kernels/76f19b63-028b-4890-80dd-ba95d18ed249/channels?session_id=c83ea599-dbfe-47a2-a6aa-162a08ad8d8c', version='HTTP/1.1', remote_ip='192.168.110.91')
    Traceback (most recent call last):
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/services/kernels/websocket.py", line 65, in get
        await super().get(kernel_id=kernel_id)
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/websocket.py", line 272, in get
        await self.ws_connection.accept_connection(self)
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/websocket.py", line 862, in accept_connection
        await self._accept_connection(handler)
      File "/home/util/anaconda3/lib/python3.10/site-packages/tornado/websocket.py", line 902, in _accept_connection
        self.selected_subprotocol = handler.select_subprotocol(subprotocols)
      File "/home/util/anaconda3/lib/python3.10/site-packages/jupyter_server/services/kernels/websocket.py", line 87, in select_subprotocol
        preferred_protocol = self.connection.kernel_ws_protocol
    AttributeError: 'NoneType' object has no attribute 'kernel_ws_protocol'
[E 2024-06-28 15:01:53.441 ServerApp] {
      "Host": "192.168.110.131:8006",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
    }
[E 2024-06-28 15:01:53.441 ServerApp] 500 GET /api/kernels/76f19b63-028b-4890-80dd-ba95d18ed249/channels?session_id=c83ea599-dbfe-47a2-a6aa-162a08ad8d8c (bbf9201741c3491bbc43584817a64c40@192.168.110.91) 60814.24ms referer=None
[I 2024-06-28 15:02:35.268 ServerApp] Saving file at /chatglm3.ipynb
[I 2024-06-28 15:02:53.435 ServerApp] Saving file at /Untitled.ipynb
[I 2024-06-28 15:03:21.003 ServerApp] Kernel restarted: 02041086-ee0e-47f7-9229-4dcd2d52d073
[I 2024-06-28 15:03:21.010 ServerApp] Starting buffering for 02041086-ee0e-47f7-9229-4dcd2d52d073:69ba60dd-8ae6-4349-b7d6-760423936ff1
[I 2024-06-28 15:03:21.018 ServerApp] Connecting to kernel 02041086-ee0e-47f7-9229-4dcd2d52d073.
[I 2024-06-28 15:03:21.018 ServerApp] Restoring connection for 02041086-ee0e-47f7-9229-4dcd2d52d073:69ba60dd-8ae6-4349-b7d6-760423936ff1
[I 2024-06-28 15:04:53.500 ServerApp] Saving file at /Untitled.ipynb
[I 2024-06-28 15:06:53.569 ServerApp] Saving file at /Untitled.ipynb
[I 2024-06-28 15:08:53.650 ServerApp] Saving file at /Untitled.ipynb
[I 2024-06-28 15:10:53.917 ServerApp] Saving file at /Untitled.ipynb
[I 2024-06-28 15:27:24.855 ServerApp] Starting buffering for 02041086-ee0e-47f7-9229-4dcd2d52d073:69ba60dd-8ae6-4349-b7d6-760423936ff1
[I 2024-06-28 15:27:24.857 ServerApp] Starting buffering for 18ee5317-6787-467c-a704-0f786157e6ce:6b920e5d-8229-457e-96f9-6c21fa63a633
